services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
      ./wait-for-it.sh db:5432 --
      alembic upgrade head &&
      cd /app/code &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

networks:
  app-network:
